Revert "libbrillo: add perfetto to pkg_deps for sanitizer builds"
This reverts commit 139a71ddd0063c8c7fd37cb507ddeff3ffceeed9.

Reason for revert: the bug is fixed in the upstream (aosp/2880957) and this workaround is unnecessary now.

Original change's description:
> libbrillo: add perfetto to pkg_deps for sanitizer builds
>
> Perfetto auto uprev failed because a harmless change from the upstream
> like aosp/2821944 breaks Perfetto's trick of saving code size if a SDK
> user (e.g. libchrome-core) doesn't enable the in-process tracing backend
> on sanitizer builds:
>
> 1. libperfetto_sdk.a is linked to libchrome-core.so, which doesn't use
> the in-process backend. The linker correctly eliminates the in-process
> backend functions rooted by
> perfetto::internal::InProcessTracingBackend::GetInstance() on sanitizer
> builds.
>
> 2. libbrillo-core.so enables tracing using libchrome-core.so. In-process
> backend isn't enabled in libbrillo-core, but the linker thinks
> perfetto::internal::InProcessTracingBackend::GetInstance() is used and
> emits an undefined reference to the function in libbrillo-core.so.
>
> 3. An executable fails to link with libbrillo-core.so because the
> function is undefined:
>
> FAILED: maitred_client:
> (linker command for maitred_client)
> ld.lld: error: undefined reference due to --no-allow-shlib-undefined:
> perfetto::internal::InProcessTracingBackend::GetInstance()
>
> This CL works around the problem by also linking libperfetto_sdk.a with
> libbrillo so the function is defined on sanitizer builds.
>
> BUG=b:315754692
> TEST=CQ dry run on amd64-generic-asan
>
> Change-Id: I71e7f63a9a63c8a9b590b76eb23d2ab4a9f78721
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5114481
> Reviewed-by: Eric Caruso <ejcaruso@chromium.org>
> Tested-by: Chinglin Yu <chinglinyu@chromium.org>
> Commit-Queue: Chinglin Yu <chinglinyu@chromium.org>
> Reviewed-by: Primiano Tucci <primiano@chromium.org>

BUG=b:315754692

Change-Id: I9eb4643002de054d3b2f24076df4ce36ed91e649
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/5144206
Auto-Submit: Chinglin Yu <chinglinyu@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Eric Caruso <ejcaruso@chromium.org>
Commit-Queue: Eric Caruso <ejcaruso@chromium.org>
NOKEYCHECK=True
GitOrigin-RevId: 783e91eeeb406be697f70e31672d76d49ce08687